from fastapi import FastAPI, UploadFile, File, HTTPException, Form
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, Response
from .models import FinalResponse, ExtractedData
from .graph import app_graph
import uuid
import uvicorn
import os
from dotenv import load_dotenv
from pathlib import Path
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
import io
import json

# Try identifying .env in current or parent directory
env_path = Path(__file__).resolve().parent.parent / '.env'
if not env_path.exists():
    env_path = Path(__file__).resolve().parent.parent.parent / '.env'
    
load_dotenv(dotenv_path=env_path)

app = FastAPI(title="PDF Claim Processing Service")

# Mount static files
app.mount("/static", StaticFiles(directory="static"), name="static")

@app.get("/")
async def read_root():
    return FileResponse("static/index.html")

@app.post("/api/process", response_model=FinalResponse)
async def process_claim(claim_id: str = Form(...), file: UploadFile = File(...)):
    if not file.filename.endswith('.pdf'):
        raise HTTPException(status_code=400, detail="File must be a PDF.")

    try:
        # Read the file
        pdf_bytes = await file.read()
        
        # Initialize Graph State
        initial_state = {
            "pdf_bytes": pdf_bytes,
            "claim_id": claim_id,
            "pages_text": {},
            "classification_result": None,
            "extracted_data": None, # Will be handled by reducer
            "logs": []
        }

        # Run Graph
        final_state = app_graph.invoke(initial_state)
        
        extracted_data = final_state.get('extracted_data')
        logs = final_state.get('logs')

        return FinalResponse(
            claim_id=claim_id,
            extracted_data=extracted_data,
            agent_logs=logs
        )

    except Exception as e:
        import traceback
        traceback.print_exc()
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/api/download-pdf")
async def generate_pdf(data: FinalResponse):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    y = height - 50
    
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, f"Claim Processing Report - {data.claim_id}")
    y -= 30
    
    c.setFont("Helvetica", 10)
    c.drawString(50, y, "Generated by AI Claim Processor")
    y -= 20
    c.line(50, y, width - 50, y)
    y -= 30
    
    # Identity
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Identity Information")
    y -= 20
    
    c.setFont("Helvetica", 10)
    id_info = data.extracted_data.identity
    if id_info:
        c.drawString(70, y, f"Patient Name: {id_info.patient_name}")
        y -= 15
        c.drawString(70, y, f"DOB: {id_info.dob}")
        y -= 15
        c.drawString(70, y, f"Policy #: {id_info.policy_number}")
        y -= 15
        c.drawString(70, y, f"ID #: {id_info.id_number}")
    else:
        c.drawString(70, y, "No identity info found.")
    y -= 30

    # Discharge
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Discharge Summary")
    y -= 20
    
    c.setFont("Helvetica", 10)
    dis_info = data.extracted_data.discharge_summary
    if dis_info:
        c.drawString(70, y, f"Diagnosis: {dis_info.diagnosis}")
        y -= 15
        c.drawString(70, y, f"Admission Date: {dis_info.admission_date}")
        y -= 15
        c.drawString(70, y, f"Discharge Date: {dis_info.discharge_date}")
        y -= 15
        c.drawString(70, y, f"Physician: {dis_info.physician_name}")
    else:
        c.drawString(70, y, "No discharge summary found.")
    y -= 30

    # Bill
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y, "Itemized Bill")
    y -= 20
    
    c.setFont("Helvetica", 10)
    bill_info = data.extracted_data.bill_data
    if bill_info:
        c.drawString(70, y, f"Total Amount: {bill_info.total_amount}")
        y -= 20
        c.drawString(70, y, "Items:")
        y -= 15
        for item in bill_info.items:
            if y < 50:
                c.showPage()
                y = height - 50
            c.drawString(90, y, f"- {item.description}: {item.amount}")
            y -= 15
    else:
        c.drawString(70, y, "No bill data found.")
        
    c.save()
    buffer.seek(0)
    
    return Response(content=buffer.getvalue(), media_type="application/pdf")

if __name__ == "__main__":
    uvicorn.run("app.main:app", host="0.0.0.0", port=8000, reload=True)
